# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helmholtzcoil_control_dockwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtWidgets
from qudi.util.widgets.advanced_dockwidget import AdvancedDockWidget
from qudi.interface.helmholtz_coil_interface import MagnetState
from qtwidgets import Toggle

class HelmholtzControlDockWidget(AdvancedDockWidget):
    """
    """
    sigMagnetStateChanged = QtCore.Signal(object)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # generate main widget and layout
        main_widget = QtWidgets.QWidget()
        main_layout = QtWidgets.QGridLayout()
        main_layout.setContentsMargins(1, 1, 1, 1)
        main_widget.setLayout(main_layout)
        self.setWidget(main_widget)

        self.label_5 = QtWidgets.QLabel()
        self.label_5.setText("Phi read (rad)")
        main_layout.addWidget(self.label_5, 2, 1, 1, 1)

        self.label_9 = QtWidgets.QLabel()
        self.label_9.setText( "Current z (A)")
        main_layout.addWidget(self.label_9, 4, 2, 1, 1)

        self.label = QtWidgets.QLabel()
        main_layout.addWidget(self.label, 0, 1, 1, 1)

        self.label_8 = QtWidgets.QLabel()
        main_layout.addWidget(self.label_8, 2, 2, 1, 1)

        self.label_11 = QtWidgets.QLabel()
        main_layout.addWidget(self.label_11, 2, 3, 1, 1)

        self.label_3 = QtWidgets.QLabel()
        main_layout.addWidget(self.label_3, 2, 0, 1, 1)

        self.setbfield_button = QtWidgets.QPushButton()
        main_layout.addWidget(self.setbfield_button, 6, 0, 1, 1)
        # self.setbfield_button.clicked.connect(
        #     lambda: self.sigMagnetStateChanged.emit(MagnetState.SETTING)
        # )

        self.label_12 = QtWidgets.QLabel()
        main_layout.addWidget(self.label_12, 4, 3, 1, 1)

        self.lineEdit_4 = QtWidgets.QLineEdit()
        main_layout.addWidget(self.lineEdit_4, 6, 3, 1, 1)
        self.lineEdit_4.setText("Line edit 4")

        self.label_4 = QtWidgets.QLabel()
        main_layout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_4.setText("label 4")

        self.theta_set_lineedit = QtWidgets.QLineEdit()
        main_layout.addWidget(self.theta_set_lineedit, 5, 0, 1, 1)
        self.theta_set_lineedit.setText("Theta lineedit")

        self.label_7 = QtWidgets.QLabel()
        main_layout.addWidget(self.label_7, 0, 2, 1, 1)

        self.bnorm_set_lineedit = QtWidgets.QLineEdit()
        main_layout.addWidget(self.bnorm_set_lineedit, 1, 0, 1, 1)
        self.bnorm_set_lineedit.setText("Bnorm lineedit")

        self.label_2 = QtWidgets.QLabel()
        main_layout.addWidget(self.label_2, 0, 0, 1, 1)

        self.label_6 = QtWidgets.QLabel()
        main_layout.addWidget(self.label_6, 4, 1, 1, 1)

        self.label_10 = QtWidgets.QLabel()
        main_layout.addWidget(self.label_10, 0, 3, 1, 1)

        self.phi_set_lineedit = QtWidgets.QLineEdit()
        main_layout.addWidget(self.phi_set_lineedit, 3, 0, 1, 1)
        self.phi_set_lineedit.setText("Phi set lineedit")


        self.label_13 = QtWidgets.QLabel()
        main_layout.addWidget(self.label_13, 6, 2, 1, 1)
        self.label_13.setText("label 13")

        self.xcurrentpolarity = QtWidgets.QLabel()
        self.xcurrentpolarity.setText("x current pol")
        main_layout.addWidget(self.xcurrentpolarity, 1, 3, 1, 1)

        self.ycurrentpolarity = QtWidgets.QLabel()
        self.ycurrentpolarity.setText("y current pol")
        main_layout.addWidget(self.ycurrentpolarity, 3, 3, 1, 1)

        self.zcurrentpolarity = QtWidgets.QLabel()
        self.zcurrentpolarity.setText("z curren pol")
        main_layout.addWidget(self.zcurrentpolarity, 5, 3, 1, 1)

        self.bnorm_read = QtWidgets.QLabel()
        self.bnorm_read.setText("bnorm")
        main_layout.addWidget(self.bnorm_read, 1, 1, 1, 1)

        self.phi_read = QtWidgets.QLabel()
        self.phi_read.setText("phi")
        main_layout.addWidget(self.phi_read, 3, 1, 1, 1)

        self.theta_read = QtWidgets.QLabel()
        self.theta_read.setText("theta")
        main_layout.addWidget(self.theta_read, 5, 1, 1, 1)

        self.currentz_read = QtWidgets.QLabel()
        self.currentz_read.setText("current z read")
        main_layout.addWidget(self.currentz_read, 5, 2, 1, 1)

        self.currenty_read = QtWidgets.QLabel()
        self.currenty_read.setText("current y read")
        main_layout.addWidget(self.currenty_read, 3, 2, 1, 1)

        self.currentx_read = QtWidgets.QLabel()
        self.currentx_read.setText("current x read")
        main_layout.addWidget(self.currentx_read, 1, 2, 1, 1)

        self.label.setText( "B norm read (mT)")
        self.label_8.setText( "Current y (A)")
        self.label_11.setText( "Polarity y")
        self.label_3.setText( "Phi (rad)")
        self.setbfield_button.setText( "Set B field")
        self.label_12.setText( "Polarity z")
        self.lineEdit_4.setText( "500")
        self.label_4.setText( "Theta (rad)")
        self.theta_set_lineedit.setText( "0")
        self.label_7.setText( "Current x (A)")
        self.bnorm_set_lineedit.setText( "0")
        self.label_2.setText( "B norm (mT)")
        self.label_6.setText( "Theta read (rad)")
        self.label_10.setText( "Polarity x")
        self.phi_set_lineedit.setText( "0")
        self.label_13.setText( "Set wait time (ms)")
